//
//  MobClickUtils.h
//  Sport
//
//  Created by haodong  on 13-8-1.
//  Copyright (c) 2013年 haodong . All rights reserved.
//

#import <Foundation/Foundation.h>


#define umeng_event_show_business_detail            @"show_business_detail"
#define umeng_event_show_venue_price                @"show_venue_price"
#define umeng_event_show_order_confirm              @"show_order_confirm"
#define umeng_event_enter_order_detail              @"enter_order_detail"
#define umeng_event_click_pay                       @"click_pay"
#define umeng_event_pay_success                     @"pay_success"
#define umeng_event_show_share_red_packet_window                @"show_share_red_packet_window"
#define umeng_event_click_share_red_packet                      @"click_share_red_packet"
#define umeng_event_home_click_message_button                   @"home_click_message_button"
#define umeng_event_message_center_page_click_notice_tab        @"message_center_page_click_notice_tab"
#define umeng_event_home_click_message_button                   @"home_click_message_button"
#define umeng_event_message_center_page_click_notice_tab        @"message_center_page_click_notice_tab"
#define umeng_event_message_center_page_click_chat_tab          @"message_center_page_click_chat_tab"
#define umeng_event_business_list_click_time                    @"business_list_click_time"
#define umeng_event_business_list_click_cancel_time             @"business_list_click_cancel_time"
#define umeng_event_business_list_click_top_filter_button       @"business_list_click_top_filter_button"

//1.94增加
#define umeng_event_click_business_detial_more_info             @"click_business_detial_more_info"
#define umeng_event_click_order_comfirm_refund_explame          @"click_order_comfirm_refund_explame"
#define umeng_event_login_for_wx                                @"login_for_wx"
#define umeng_event_login_for_qq                                @"login_for_qq"
#define umeng_event_login_for_sina                              @"login_for_sina"
#define umeng_event_bind_for_phone                              @"bind_for_phone"
#define umeng_event_bind_for_sina                               @"bind_for_sina"
#define umeng_event_bind_for_qq                                 @"bind_for_qq"
#define umeng_event_bind_for_wx                                 @"bind_for_wx"


#define umeng_event_enter_call_book                 @"enter_call_book"
#define umeng_event_summit_call_book                @"summit_call_book"
#define umeng_event_enter_create_activity_page      @"enter_create_activity_page"
#define umeng_event_submit_create_activity          @"submit_create_activity"
#define umeng_event_click_promise_user_require      @"click_promise_user_require"
#define umeng_event_enter_user_detail               @"enter_user_detail"
#define umeng_event_user_detail_click_chat          @"user_detail_click_chat"
#define umeng_event_user_detail_click_invite        @"user_detail_click_invite"
#define umeng_event_user_detail_click_give_lemon    @"user_detail_click_give_lemon"
#define umeng_event_user_detail_click_report        @"user_detail_click_report"
#define umeng_event_user_detail_click_album         @"user_detail_click_album"
#define umeng_event_user_detail_click_equipment     @"user_detail_click_equipment"
#define umeng_event_user_detail_click_current_activity @"user_detail_click_current_activity"
#define umeng_event_enter_activity_detail           @"enter_activity_detail"
#define umeng_event_click_promise                   @"click_promise"
#define umeng_event_search_business                 @"search_business"
#define umeng_event_home_page_click_banner              @"home_page_click_banner"
#define umeng_event_home_page_click_business            @"home_page_click_business"
#define umeng_event_home_page_click_user                @"home_page_click_user"
#define umeng_event_home_page_click_change_one_group    @"home_page_click_change_one_group"

#define umeng_event_enter_pay           @"enter_pay"
#define umeng_event_pay_cancel          @"pay_cancel"
#define umeng_event_pay_failure         @"pay_failure"
#define umeng_event_click_draw_button                   @"click_draw_button"
#define umeng_event_click_home_booking_button           @"click_home_booking_button"
#define umeng_event_enter_bind_phone                    @"enter_bind_phone"
#define umeng_event_enter_edit_user_info                @"enter_edit_user_info"
#define umeng_event_enter_lucky_draw                    @"enter_lucky_draw"
#define umeng_event_enter_my_point                      @"enter_my_point"
#define umeng_event_enter_point_goods_detail            @"enter_point_goods_detail"
#define umeng_event_enter_promotion_detail              @"enter_promotion_detail"
#define umeng_event_enter_promotion_order_confirm       @"enter_promotion_order_confirm"
#define umeng_event_enter_write_review                  @"enter_write_review"

#define	umeng_event_click_map_from_home                 @"click_map_from_home"
#define	umeng_event_home_page_click_category            @"home_page_click_category"
#define	umeng_event_promotion_list                      @"promotion_list"
#define	umeng_event_home_click_history                  @"home_click_history"
#define	umeng_event_click_map_from_business_list        @"click_map_from_business_list"
#define	umeng_event_business_list_filter_category       @"business_list_filter_category"
#define	umeng_event_business_list_filter_region         @"business_list_filter_region"
#define	umeng_event_business_list_filter_sort           @"business_list_filter_sort"
#define	umeng_event_business_detail_click_gallery       @"business_detail_click_gallery"
#define	umeng_event_business_detail_click_collect       @"business_detail_click_collect"
#define	umeng_event_business_detail_click_share         @"business_detail_click_share"
#define	umeng_event_business_detail_click_all_review	@"business_detail_click_all_review"
#define	umeng_event_business_detail_click_phone         @"business_detail_click_phone"
#define	umeng_event_business_detail_click_map           @"business_detail_click_map"
#define	umeng_event_venue_page_switch_booking_date      @"venue_page_switch_booking_date"
#define	umeng_event_venue_page_click_order_button       @"venue_page_click_order_button"
#define	umeng_event_venue_page_show_unpaid_order        @"venue_page_show_unpaid_order"
#define	umeng_event_confirm_order_click_coupon          @"confirm_order_click_coupon"
#define	umeng_event_confirm_order_click_activity        @"confirm_order_click_activity"
#define	umeng_event_confirm_order_click_money           @"confirm_order_click_money"
#define	umeng_event_pay_success_click_point_shop        @"pay_success_click_point_shop"
#define	umeng_event_pay_success_click_help              @"pay_success_click_help"
#define	umeng_event_pay_success_click_share             @"pay_success_click_share"
#define	umeng_event_order_detail_click_refund_rule      @"order_detail_click_refund_rule"
#define	umeng_event_order_detail_click_refund           @"order_detail_click_refund"
#define	umeng_event_order_detail_click_qrcode           @"order_detail_click_qrcode"
#define	umeng_event_order_detail_click_business         @"order_detail_click_business"
#define	umeng_event_order_detail_click_share            @"order_detail_click_share"
#define	umeng_event_order_detail_click_forward          @"order_detail_click_forward"
#define	umeng_event_order_list_click_cancell_status     @"order_list_click_cancell_status"

#define	umeng_event_my_page_click_card                  @"my_page_click_card"
#define	umeng_event_card_page_click_add_card            @"card_page_click_add_card"
#define	umeng_event_card_login_click_get_code           @"card_login_click_get_code"
#define	umeng_event_card_login_click_help               @"card_login_click_help"
#define	umeng_event_card_scan_result                    @"card_scan_result"
#define	umeng_event_card_detail                         @"card_detail"
#define	umeng_event_card_detail_click_set               @"card_detail_click_set"
#define	umeng_event_card_detail_click_book              @"card_detail_click_book"
#define	umeng_event_card_detail_click_recharge          @"card_detail_click_recharge"
#define	umeng_event_card_detail_click_unbind            @"card_detail_click_unbind"
#define	umeng_event_card_recharge_switch_goods          @"card_recharge_switch_goods"
#define	umeng_event_card_detail_unbind_success          @"card_detail_unbind_success"
#define	umeng_event_card_recharge_click_pay             @"card_recharge_click_pay"
#define	umeng_event_card_recharge_success               @"card_recharge_success"
#define	umeng_event_card_order_success                  @"card_order_success"
#define	umeng_event_pay_success_click_order_detail		@"pay_success_click_order_detail"
#define	umeng_event_order_detail_click_card_refund		@"order_detail_click_card_refund"
#define	umeng_event_order_detail_card_refund_success	@"order_detail_card_refund_success"
#define	umeng_event_card_help_page                      @"card_help_page"
#define	umeng_event_card_bind                           @"card_bind"
#define	umeng_event_business_detail_click_image_info	@"business_detail_click_image_info"
#define	umeng_event_card_recharge_pay_cancel            @"card_recharge_pay_cancel"
#define	umeng_event_card_recharge_pay_failure           @"card_recharge_pay_failure"

#define	umeng_event_click_tab_bar_forum                         @"click_tab_bar_forum"
#define	umeng_event_click_tab_bar_coach                         @"click_tab_bar_coach"
#define	umeng_event_forum_home_click_hot_post_list_title        @"forum_home_click_hot_post_list_title"
#define	umeng_event_forum_home_hot_load_more                    @"forum_home_hot_load_more"
#define	umeng_event_forum_home_click_forum_list_title           @"forum_home_click_forum_list_title"
#define	umeng_event_forum_home_click_activity                   @"forum_home_click_activity"
#define	umeng_event_forum_home_click_people_nearby              @"forum_home_click_people_nearby"
#define	umeng_event_forum_home_click_search                     @"forum_home_click_search"
#define	umeng_event_forum_search_click_history                  @"forum_search_click_history"
#define	umeng_event_forum_search_click_result                   @"forum_search_click_result"
#define	umeng_event_forum_search_click_clear                    @"forum_search_click_clear"
#define	umeng_event_forum_search_click_cancel                   @"forum_search_click_cancel"
#define	umeng_event_forum_home_click_message                    @"forum_home_click_message"
#define	umeng_event_forum_message_list_click_content            @"forum_message_list_click_content"
#define	umeng_event_forum_message_list_click_user               @"forum_message_list_click_user"
#define	umeng_event_forum_post_list_click_user                  @"forum_post_list_click_user"
#define	umeng_event_forum_post_list_click_image                 @"forum_post_list_click_image"
#define	umeng_event_forum_post_list_click_forum_name            @"forum_post_list_click_forum_name"
#define	umeng_event_forum_post_list_click_post_entrance         @"forum_post_list_click_post_entrance"
#define	umeng_event_forum_post_detail_click_comment_user        @"forum_post_detail_click_comment_user"
#define	umeng_event_forum_post_detail_click_input               @"forum_post_detail_click_input"
#define	umeng_event_forum_post_detail_click_send                @"forum_post_detail_click_send"
#define	umeng_event_forum_post_detail_click_top_forum_entrance	@"forum_post_detail_click_top_forum_entrance"
#define	umeng_event_business_detail_click_forum_entrance        @"business_detail_click_forum_entrance"
#define	umeng_event_order_detail_click_forum_entrance           @"order_detail_click_forum_entrance"
#define	umeng_event_pay_success_click_forum_entrance            @"pay_success_click_forum_entrance"
#define	umeng_event_forum_detail_click_create                   @"forum_detail_click_create"
#define	umeng_event_forum_detail_load_more                      @"forum_detail_load_more"
#define	umeng_event_forum_create_post_click_cancel              @"forum_create_post_click_cancel"
#define	umeng_event_forum_create_post_click_send                @"forum_create_post_click_send"
#define	umeng_event_forum_create_post_click_add_image           @"forum_create_post_click_add_image"
#define	umeng_event_forum_create_post_click_input               @"forum_create_post_click_input"
#define	umeng_event_user_detail_click_edit                      @"user_detail_click_edit"
#define	umeng_event_user_detail_click_avatar                    @"user_detail_click_avatar"
#define	umeng_event_user_detail_click_often_business            @"user_detail_click_often_business"
#define	umeng_event_user_detail_click_post                      @"user_detail_click_post"
#define	umeng_event_user_info_edit_click_avatar                 @"user_info_edit_click_avatar"
#define	umeng_event_user_info_edit_click_nickname               @"user_info_edit_click_nickname"
#define	umeng_event_user_info_edit_click_gender                 @"user_info_edit_click_gender"
#define	umeng_event_user_info_edit_click_city                   @"user_info_edit_click_city"
#define	umeng_event_user_info_edit_click_signture               @"user_info_edit_click_signture"

#define	umeng_event_month_introduce_add                             @"month_introduce_add"
#define	umeng_event_month_introduce_refuse                          @"month_introduce_refuse"
#define	umeng_event_month_introduce_outside                         @"month_introduce_outside"
#define	umeng_event_month_card_qrcode                               @"month_card_qrcode"
#define	umeng_event_month_card_signin                               @"month_card_signin"
#define	umeng_event_month_card_upload_portrait                      @"month_card_upload_portrait"
#define	umeng_event_month_click_sport_assistant                     @"month_click_sport_assistant"
#define	umeng_event_month_click_exercise                            @"month_click_exercise"
#define	umeng_event_month_click_course                              @"month_click_course"
#define	umeng_event_month_click_recommend_course                    @"month_click_recommend_course"
#define	umeng_event_month_click_recommend_venues_list               @"month_click_recommend_venues_list"
#define	umeng_event_month_click_all_venues_list                     @"month_click_all_venues_list"
#define	umeng_event_month_venues_list_categories_screening          @"month_venues_list_categories_screening"
#define	umeng_event_month_venues_list_area_screening                @"month_venues_list_area_screening"
#define	umeng_event_month_click_tab_course                          @"month_click_tab_course"
#define	umeng_event_month_click_recommend_course_list               @"month_click_recommend_course_list"
#define	umeng_event_month_click_all_course_list                     @"month_click_all_course_list"
#define	umeng_event_month_course_list_categories_screening          @"month_course_list_categories_screening"
#define	umeng_event_month_course_list_area_screening                @"month_course_list_area_screening"
#define	umeng_event_month_course_list_time_screening                @"month_course_list_time_screening"
#define	umeng_event_month_click_tab_exercise                        @"month_click_tab_exercise"
#define	umeng_event_month_business_detail_click_share               @"month_business_detail_click_share"
#define	umeng_event_month_business_detail_click_gallery             @"month_business_detail_click_gallery"
#define	umeng_event_month_business_detail_click_sport_gallery       @"month_business_detail_click_sport_gallery"    //暂没添加
#define	umeng_event_month_business_detail_click_service_gallery     @"month_business_detail_click_service_gallery"  //暂没添加
#define	umeng_event_month_business_detail_click_phone               @"month_business_detail_click_phone"
#define	umeng_event_month_business_detail_click_address             @"month_business_detail_click_address"
#define	umeng_event_month_business_detail_click_buy                 @"month_business_detail_click_buy"
#define	umeng_event_month_business_detail_click_upload_portrait     @"month_business_detail_click_upload_portrait"
#define	umeng_event_month_course_detail_click_share                 @"month_course_detail_click_share"
#define	umeng_event_month_course_detail_click_business              @"month_course_detail_click_business"
#define	umeng_event_month_course_detail_click_phone                 @"month_course_detail_click_phone"
#define	umeng_event_month_course_detail_click_address               @"month_course_detail_click_address"
#define	umeng_event_month_course_detail_click_book                  @"month_course_detail_click_book"
#define	umeng_event_month_course_detail_click_buy                   @"month_course_detail_click_buy"
#define	umeng_event_month_course_detail_click_upload_portrait       @"month_course_detail_click_upload_portrait"
#define	umeng_event_month_buy_club_click_know_more                  @"month_buy_club_click_know_more"
#define	umeng_event_month_buy_club_click_count_increase             @"month_buy_club_click_count_increase"
#define	umeng_event_month_buy_club_click_count_decrease             @"month_buy_club_click_count_decrease"
#define	umeng_event_month_buy_club_click_count_edit                 @"month_buy_club_click_count_edit"
#define	umeng_event_month_buy_club_click_coupon                     @"month_buy_club_click_coupon"     //暂没添加
#define	umeng_event_month_set_portrait_click_upload                 @"month_set_portrait_click_upload"
#define	umeng_event_month_set_portrait_click_finish                 @"month_set_portrait_click_finish"
#define	umeng_event_month_sports_assistant_click_record             @"month_sports_assistant_click_record"
#define	umeng_event_month_sports_assistant_click_notic              @"month_sports_assistant_click_notic"
#define	umeng_event_month_sports_assistant_click_introduce          @"month_sports_assistant_click_introduce"
#define	umeng_event_month_sports_assistant_click_phone              @"month_sports_assistant_click_phone"
#define	umeng_event_month_sports_assistant_click_address            @"month_sports_assistant_click_address"
#define	umeng_event_month_sports_assistant_click_dead_line          @"month_sports_assistant_click_dead_line"
#define	umeng_event_month_sports_assistant_click_dead_line_close	@"month_sports_assistant_click_dead_line_close"
#define	umeng_event_month_sports_record_click_left_time             @"month_sports_record_click_left_time"
#define	umeng_event_month_sports_record_click_tab_business          @"month_sports_record_click_tab_business"
#define	umeng_event_month_sports_record_click_tab_course            @"month_sports_record_click_tab_course"
#define	umeng_event_month_sports_record_click_business              @"month_sports_record_click_business"
#define	umeng_event_month_sports_record_click_course                @"month_sports_record_click_course"

#define	umeng_event_click_mine_balance                              @"click_mine_balance"
#define	umeng_event_click_mine_ticket                               @"click_mine_ticket"
#define	umeng_event_click_wallet_failure_ticket                     @"click_wallet_failure_ticket"
#define	umeng_event_click_wallet_balance                            @"click_wallet_balance"
#define	umeng_event_click_wallet_integer                            @"click_wallet_integer"
#define	umeng_event_click_wallet_bind_ticket                        @"click_wallet_bind_ticket"
#define	umeng_event_click_wallet_explanation                        @"click_wallet_explanation"
#define	umeng_event_click_balance_pay_password                      @"click_balance_pay_password"
#define	umeng_event_click_balance_edit                              @"click_balance_edit"
#define	umeng_event_click_balance_charge                            @"click_balance_charge"
#define	umeng_event_click_balance_explanation                       @"click_balance_explanation"
#define	umeng_event_click_balance_record                            @"click_balance_record"
#define	umeng_event_click_bind_ticket_my_ticket                     @"click_bind_ticket_my_ticket"
#define	umeng_event_click_bind_ticket_bind_btn                      @"click_bind_ticket_bind_btn"
#define	umeng_event_click_bind_ticket_explanation                   @"click_bind_ticket_explanation"
#define	umeng_event_click_my_ticket_failure_ticket                  @"click_my_ticket_failure_ticket"
#define	umeng_event_click_failure_tab_sport_stamps                  @"click_failure_tab_sport_stamps"
#define	umeng_event_click_failure_tab_coupon                        @"click_failure_tab_coupon"
#define	umeng_event_use_coupon                                      @"use_coupon"
#define	umeng_event_use_sport_stamps                                @"use_sport_stamps"

#define	umeng_event_click_coach_list_more               @"click_coach_list_more"
#define	umeng_event_click_coach_list_categories         @"click_coach_list_categories"
#define	umeng_event_click_coach_list_sex                @"click_coach_list_sex"
#define	umeng_event_click_coach_list_sort               @"click_coach_list_sort"
#define	umeng_event_click_coach_list_caoch_introduce    @"click_coach_list_caoch_introduce"
#define	umeng_event_click_coach_detail_photo            @"click_coach_detail_photo"
#define	umeng_event_sliding_coach_detail_photo          @"sliding_coach_detail_photo"  //暂没法统计
#define	umeng_event_click_coach_detail_portrait         @"click_coach_detail_portrait"
#define	umeng_event_click_coach_detail_more_comment		@"click_coach_detail_more_comment"
#define	umeng_event_click_coach_detail_booking          @"click_coach_detail_booking"
#define	umeng_event_click_coach_detail_chat             @"click_coach_detail_chat"
#define	umeng_event_click_coach_detail_comment_photo	@"click_coach_detail_comment_photo"
#define	umeng_event_click_coach_order_list              @"click_coach_order_list"
#define	umeng_event_click_coach_order_introduce         @"click_coach_order_introduce"
#define	umeng_event_click_coach_order_phone             @"click_coach_order_phone"
#define	umeng_event_click_coach_order_bottom            @"click_coach_order_bottom"
#define	umeng_event_click_coach_order_complanit         @"click_coach_order_complanit"


#define	umeng_event_click_home_recommend_venue                 @"click_home_recommend_venue"
#define	umeng_event_click_home_recommend_course                @"click_home_recommend_course"
#define	umeng_event_click_home_ckeck_more_button               @"click_home_ckeck_more_button"
#define	umeng_event_click_venue_details_promptly_buy_button       @"click_venue_details_promptly_buy_button"
#define	umeng_event_click_venue_details_people_commodity       @"click_venue_details_people_commodity"
#define	umeng_event_click_my_wallet_club_button                @"click_my_wallet_club_button"
#define	umeng_event_click_club_introduce_buy_club_button                @"click_club_introduce_buy_club_button"
#define	umeng_event_show_affirm_order_club_recommend_enter                @"show_affirm_order_club_recommend_enter"
#define	umeng_event_click_affirm_order_club_recommend_enter                @"click_affirm_order_club_recommend_enter"
#define	umeng_event_click_order_details_cancel_order_button                @"click_order_details_cancel_order_button"
#define	umeng_event_click_order_details_affirm_refund_window                @"click_order_details_affirm_refund_window"
#define	umeng_event_click_order_details_cancel_refund_window                @"click_order_details_cancel_refund_window"
#define	umeng_event_click_affirm_order_cancel_club_order_window                @"click_affirm_order_cancel_club_order_window"
#define	umeng_event_click_affirm_order_config_club_order_window                @"click_affirm_order_config_club_order_window"
#define umeng_event_click_submit_order_button                       @"click_submit_order_button"
#define umeng_event_confirm_order_click_pay_type                    @"confirm_order_click_pay_type"

#define umeng_event_mwphoto_done_button                    @"mwphoto_done_button"
#define umeng_event_mwphoto_single_tap                    @"mwphoto_single_tap"

#define umeng_event_click_all_search_record               @"click_all_search_record"
#define umeng_event_click_recommended_key_word            @"click_recommended_key_word"
#define umeng_event_click_search_input_clear              @"click_search_input_clear"
#define umeng_event_click_search_window                   @"click_search_window"
#define umeng_event_click_exit_search_result              @"click_exit_search_result"
#define umeng_event_click_msg_act                         @"click_msg_act"
#define umeng_event_click_msg_forum                       @"click_msg_forum"
#define umeng_event_click_msg_act_list                    @"click_msg_act_list"
#define umeng_event_click_quick_booking                   @"click_quick_booking"
#define umeng_event_show_nearby_bussiness                 @"show_nearby_bussiness"
#define umeng_event_click_nearby_bussiness                @"click_nearby_bussiness"
#define umeng_event_click_questionnaire                   @"click_questionnaire"
#define umeng_event_click_feed_back                       @"click_feed_back"
#define umeng_event_notify_friends                        @"notify_friends"
#define umeng_event_confirm_pay_way                       @"confirm_pay_way"

#define umeng_event_enter_search                      @"enter_search"
#define umeng_event_click_clear_search_record @"click_clear_search_record"
#define umeng_event_click_history_search_record @"click_history_search_record"
#define umeng_event_click_search_window_form_search @"click_search_window_form_search"
#define umeng_event_click_search_result @"click_search_result"

#define umeng_event_show_quick_booking @"show_quick_booking"
#define umeng_event_show_order_confirm_from_quick_booking @"show_order_confirm_from_quick_booking"
#define umeng_event_click_order_submit_from_quick_booking @"click_order_submit_from_quick_booking"

//2.0.0添加的
#define umeng_event_visit_court_join_list                @"visit_court_join_list"      //球局列表的访问量
#define umeng_event_click_sign_in_button                 @"click_sign_in_button"
#define umeng_event_show_sign_in_succeed                 @"show_sign_in_succeed"
#define umeng_event_sign_in_share_success                @"sign_in_share_success"
#define umeng_event_show_sign_in_record                  @"show_sign_in_record"
#define umeng_event_sign_in_record_source                @"sign_in_record_source"
#define umeng_event_sign_in_record_addition              @"sign_in_record_addition"
#define umeng_event_sign_in_duration                     @"sign_in_duration"

#define umeng_event_welcome_court_join_button @"welcome_court_join_button"
#define umeng_event_court_join_modify_avatar @"court_join_modify_avatar"
#define umeng_event_court_join_modify_nickname @"court_join_modify_nickname"
#define umeng_event_court_join_modify_sign @"court_join_modify_sign"
#define umeng_event_court_join_sponsor_click_share_button @"court_join_sponsor_click_share_button"
#define umeng_event_court_join_sponsor_share_success @"court_join_sponsor_share_success"
#define umeng_event_court_join_sponsor_order_im @"court_join_sponsor_order_im"
#define umeng_event_court_join_sponsor_order_phone @"court_join_sponsor_order_phone"

#define umeng_event_court_join_detail_share_success @"court_join_detail_share_success"
#define umeng_event_court_join_detail_im @"court_join_detail_im"
#define umeng_event_court_join_confirm_order @"court_join_confirm_order"
#define umeng_event_court_join_pay_request @"court_join_pay_request"
#define umeng_event_court_join_pay_success @"court_join_pay_success"
#define umeng_event_court_join_order_im @"court_join_order_im"
#define umeng_event_court_join_order_phone @"court_join_order_phone"


@interface MobClickUtils : NSObject

//+ (int)getIntValueByKey:(NSString*)key defaultValue:(int)defaultValue;
//+ (double)getDoubleValueByKey:(NSString*)key defaultValue:(double)defaultValue;
//+ (CGFloat)getFloatValueByKey:(NSString*)key defaultValue:(CGFloat)defaultValue;
//+ (NSString*)getStringValueByKey:(NSString*)key defaultValue:(NSString*)defaultValue;
//+ (int)getBoolValueByKey:(NSString*)key defaultValue:(BOOL)defaultValue;

+ (void)event:(NSString *)eventId;
+ (void)event:(NSString *)eventId label:(NSString *)label;

+ (void)beginLogPageView:(NSString *)pageName;
+ (void)endLogPageView:(NSString *)pageNam;

+ (void)beginEvent:(NSString *)eventId label:(NSString *)label;
+ (void)beginEvent:(NSString *)eventId;

+ (void)endEvent:(NSString *)eventId label:(NSString *)label;
+ (void)endEvent:(NSString *)eventId;

@end
