source 'https://github.com/qhd/NMPublic.git'
source 'https://github.com/CocoaPods/Specs.git'
target 'Sport' do
    inhibit_all_warnings!
    pod 'RongCloudIMKit', '2.6.10'
    pod 'AMapSearch', '~> 3.0.0'
    pod 'SSZipArchive','~> 1.1'
    pod 'UITableView+FDTemplateLayoutCell','1.4'
    pod 'UMengAnalytics-NO-IDFA', '~> 3.6.7'
    pod 'JPush-iOS-SDK', '~> 2.1.0'
    pod 'NJKWebViewProgress','0.2.3'
    pod 'MWPhotoBrowserForSport','~> 1.3'
    pod 'WeiboSDK', :podspec => 'https://raw.githubusercontent.com/jiangyancong/NMSNS/master/WeiboSDK.podspec'
    pod 'AGImagePickerControllerForSport','~> 2.0.3'
    pod 'SVProgressHUD', '2.0.3'
    pod 'MJRefresh', '3.1.10'
    pod 'NMPublicRepo', '1.4'
    pod 'AFNetworking', '3.1.0'
    pod 'AFNetworkActivityLogger',:git => 'https://github.com/AFNetworking/AFNetworkActivityLogger.git', :branch => '3_0_0'
    pod 'Fabric', '1.6.8'
    pod 'Crashlytics', '3.7.3'
end
target 'SportTests' do
  inherit! :search_paths
  pod 'OCMock', '~> 3.3'
  pod 'OCHamcrest', '~> 5.0'
end