//
//  NotificationMacro.h
//  Sport
//
//  Created by haodong  on 14-5-17.
//  Copyright (c) 2014年 haodong . All rights reserved.
//

#import <Foundation/Foundation.h>

#define NOTIFICATION_NAME_CHANGE_TIPS_COUNT @"NOTIFICATION_NAME_CHANGE_TIPS_COUNT"

#define NOTIFICATION_NAME_RECEIVE_CHAT_PUSH @"NOTIFICATION_NAME_RECEIVE_CHAT_PUSH"

#define NOTIFICATION_NAME_FINISH_WECHAT_PAY @"NOTIFICATION_NAME_FINISH_WECHAT_PAY"

#define NOTIFICATION_NAME_FINISH_WECHAT_AUTH @"NOTIFICATION_NAME_FINISH_WECHAT_AUTH"

#define NOTIFICATION_NAME_WECHAT_LOGIN_SUCCESS @"NOTIFICATION_NAME_WECHAT_LOGIN_SUCCESS"
#define NOTIFICATION_NAME_WECHAT_BIND_SUCCESS @"NOTIFICATION_NAME_WECHAT_BIND_SUCCESS"

#define NOTIFICATION_NAME_FINISH_SHARE_TO_WECHAT    @"NOTIFICATION_NAME_FINISH_SHARE_TO_WECHAT"
#define NOTIFICATION_NAME_SHARE_TO_WECHAT_FAIL    @"NOTIFICATION_NAME_SHARE_TO_WECHAT_FAIL"

#define NOTIFICATION_NAME_FINISH_SHARE_TO_SINA    @"NOTIFICATION_NAME_FINISH_SHARE_TO_SINA"

#define NOTIFICATION_NAME_DID_CHANGE_CITY    @"NOTIFICATION_NAME_DID_CHANGE_CITY"

#define NOTIFICATION_NAME_FINISH_QUERY_STATIC_DATA    @"NOTIFICATION_NAME_FINISH_QUERY_STATIC_DATA"

#define NOTIFICATION_NAME_FINISH_SHOW_START_PAGE    @"NOTIFICATION_NAME_FINISH_SHOW_START_PAGE"

#define NOTIFICATION_NAME_FINISH_SHOW_BOOT_PAGE    @"NOTIFICATION_NAME_FINISH_SHOW_BOOT_PAGE"

#define NOTIFICATION_NAME_FINISH_WRITE_REVIEW    @"NOTIFICATION_NAME_FINISH_WRITE_REVIEW"

#define NOTIFICATION_NAME_FINISH_APPLY_REFUND    @"NOTIFICATION_NAME_FINISH_APPLY_REFUND"

#define NOTIFICATION_NAME_FINISH_PAY_ORDER    @"NOTIFICATION_NAME_FINISH_PAY_ORDER"

#define NOTIFICATION_NAME_FINISH_EDIT_USER_INFO    @"NOTIFICATION_NAME_FINISH_EDIT_USER_INFO"

#define NOTIFICATION_NAME_DID_LOG_OUT    @"NOTIFICATION_NAME_DID_LOG_OUT"

#define NOTIFICATION_NAME_DID_LOG_IN  @"NITIFICATION_NAME_DID_LOG_IN"

#define NOTIFICATION_LOADING_COACH_ORDER_INFO_COMPLETED @"NOTIFICATION_LOADING_COACH_ORDER_INFO_COMPLETED"

#define NOTIFICATION_NAME_FINISH_COACH_ORDER    @"NOTIFICATION_NAME_FINISH_COACH_ORDER"

#define NOTIFICATION_NAME_CANCEL_COACH_ORDER    @"NOTIFICATION_NAME_CANCEL_COACH_ORDER"
#define NOTIFICATION_NAME_CANCEL_COACH_ADDRESS_INPUT   @"NOTIFICATION_NAME_CANCEL_COACH_ADDRESS_INPUT"

#define NOTIFICATION_NAME_ACCESS_TOKEN_FAILED   @"NOTIFICATION_NAME_ACCESS_TOKEN_FAILED"
#define NOTIFICATION_NAME_LOGIN_ENCODE_ERROR    @"NOTIFICATION_NAME_LOGIN_ENCODE_ERROR"
#define NOTIFICATION_NAME_ACCESS_TOKEN_SUCESS    @"NOTIFICATION_NAME_ACCESS_TOKEN_SUCESS"

@interface NotificationMacro : NSObject

@end
