//
//  SportNetworkContent.h
//  Sport
//
//  Created by haodong  on 13-6-6.
//  Copyright (c) 2013年 haodong . All rights reserved.
//

#import <Foundation/Foundation.h>

#define SPORT_DEFAULT_HOST                  [ConfigData defaultHost]
#define GS_DEFAULT_HOST                     [ConfigData gsDefaultHost]
#define GS_URL_USER                         [NSString stringWithFormat:@"%@/user", GS_DEFAULT_HOST]
#define GS_URL_ORDER                        [NSString stringWithFormat:@"%@/order", GS_DEFAULT_HOST]
#define GS_URL_VENUE                        [NSString stringWithFormat:@"%@/venue", GS_DEFAULT_HOST]
#define GS_URL_INDEX                        [NSString stringWithFormat:@"%@/index", GS_DEFAULT_HOST]
#define GS_URL_SMS                          [NSString stringWithFormat:@"%@/sms", GS_DEFAULT_HOST]
#define GS_URL_USERCARD                     [NSString stringWithFormat:@"%@/usercard", GS_DEFAULT_HOST]
#define GS_URL_COACH                        [NSString stringWithFormat:@"%@/coach",GS_DEFAULT_HOST]

#define GS_URL_PAY                          [NSString stringWithFormat:@"%@/pay", GS_DEFAULT_HOST]
#define GS_URL_TICKET                       [NSString stringWithFormat:@"%@/ticket", GS_DEFAULT_HOST]
#define GS_URL_SMS                          [NSString stringWithFormat:@"%@/sms", GS_DEFAULT_HOST]
#define GS_URL_IM                           [NSString stringWithFormat:@"%@/im", GS_DEFAULT_HOST]
#define SPORT_URL_DEFAULT_APP_V2            [NSString stringWithFormat:@"%@/app/v2", SPORT_DEFAULT_HOST]
#define SPORT_URL_DEFAULT_APP_USERCARD      [NSString stringWithFormat:@"%@/app/usercard", SPORT_DEFAULT_HOST]
#define SPORT_URL_DEFAULT_APP_PAYPASSWORD   [NSString stringWithFormat:@"%@/app/paypassword", SPORT_DEFAULT_HOST]
#define SPORT_URL_DEFAULT_APP_MONTHCARD     [NSString stringWithFormat:@"%@/app/moncard", SPORT_DEFAULT_HOST]
#define SPORT_URL_DEFAULT_APP_COACH         [NSString stringWithFormat:@"%@/app/coach", SPORT_DEFAULT_HOST]
#define SPORT_URL_DEFAULT_APP_IM            [NSString stringWithFormat:@"%@/app/im", SPORT_DEFAULT_HOST]
#define SPORT_URL_DEFAULT_APP_TICKET         [NSString stringWithFormat:@"%@/app/ticket", SPORT_DEFAULT_HOST]
#define SPORT_URL_DEFAULT_APP_COUPON         [NSString stringWithFormat:@"%@/app/coupon", SPORT_DEFAULT_HOST]

#define SPORT_URL_DEFAULT_PAY               [NSString stringWithFormat:@"%@/pay", SPORT_DEFAULT_HOST]
#define SPORT_URL_DEFAUL_VENUE              [NSString stringWithFormat:@"%@/venue", SPORT_DEFAULT_HOST]
#define SPORT_URL_DEFAULT_USER_API          [NSString stringWithFormat:@"%@/userapi", SPORT_DEFAULT_HOST]

#define SPORT_URL_DEFAULT_APP_V2_VENUE       [NSString stringWithFormat:@"%@/venue", SPORT_URL_DEFAULT_APP_V2]

#define SPORT_FORUM_HOST                    [ConfigData forumHost]
#define SPORT_URL_FORUM_POST                [NSString stringWithFormat:@"%@/post", SPORT_FORUM_HOST]
#define SPORT_URL_FORUM_IMAGE               [NSString stringWithFormat:@"%@/image", SPORT_FORUM_HOST]
#define SPORT_URL_FORUM_MESSAGE             [NSString stringWithFormat:@"%@/message", SPORT_FORUM_HOST]

#define SPORT_URL_DEFAUL_ORDER              [NSString stringWithFormat:@"%@/order", SPORT_DEFAULT_HOST]

//**************** parameter *******************
#define PARA_DISPLAY_WIDTH          @"display_width"
#define PARA_DISPLAY_HEIGHT         @"display_height"
#define PARA_VER                    @"ver"
#define PARA_VERSION                @"version"
#define PARA_ZIPFILE                @"zipfile"
#define PARA_SEARCHCITYID           @"SEARCHCITYID"
#define PARA_SEARCHVERSION          @"SEARCHVERSION"
#define PARA_API_SIGN               @"api_sign"
#define PARA_UTM_SOURCE             @"utm_source"
#define PARA_UTM_MEDIUM             @"utm_medium"
#define PARA_APP_VERSION            @"app_version"
#define PARA_SYSTEM_VERSION         @"system_version"
#define PARA_CLIENT_TIME            @"client_time"
#define PARA_ACTION                 @"action"
#define PARA_PHONE                  @"phone"
#define PARA_PHONE_ENCODE           @"phone_encode"
#define PARA_STATUS                 @"status"
#define PARA_VERIFICATION           @"verification"
#define PARA_PASSWORD               @"password"
#define PARA_USER_ID                @"user_id"
#define PARA_V_USER_ID              @"v_user_id"
#define PARA_MY_RULES               @"my_rules"
#define PARA_RULES_TITLE            @"rules_title"
#define PARA_RULES_LEVEL            @"rules_level"
#define PARA_RULES_DETAIL_URL       @"rules_detail_url"
#define PARA_RULES_IS_DISPLAY       @"is_open"
#define PARA_RULES_ICON_URL         @"rules_icon_url"

#define PARA_LOGIN_ENCODE           @"login_encode"
#define PARA_NICK_NAME              @"nick_name"
#define PARA_BIRTHDAY               @"birthday"
#define PARA_GENDER                 @"gender"
#define PARA_AGE                    @"age"
#define PARA_AVATAR                 @"avatar"
#define PARA_LEFT_JOIN_NUM          @"left_join_num"
#define PARA_COURT_JOIN_MAX_PLAYERS @"court_join_max_players"
#define PARA_JOIN_NUM               @"join_num"
#define PARA_COURT_JOIN_CONTINUOUS  @"court_join_continuous"
#define PARA_OPEN_INFO              @"open_info"
#define PARA_OPEN_TYPE              @"open_type"
#define PARA_OPEN_USER_ID           @"open_user_id"
#define PARA_OPEN_ID                @"open_id"
#define PARA_UNION_ID               @"union_id"
#define PARA_OPEN_NICK_NAME         @"open_nick_name"
#define PARA_ACCESS_TOKEN           @"access_token"
#define PARA_CREDIT                 @"credit"
#define PARA_BEEN_COURT_LIST        @"been_court_list"
#define PARA_HOUR_CNT               @"hour_cnt"
#define PARA_CATEGORIES             @"categories"
#define PARA_MONCARD_CATEGORIES     @"moncard_categories"
#define PARA_ENTRY                  @"entry"
#define PARA_CATEGORY_ID            @"category_id"
#define PARA_CATEGORY_NAME          @"category_name"
#define PARA_IS_CHOOSE_CATEGORY     @"is_choose_category"
#define PARA_IS_INDEX_CATEGORY      @"is_index_category"
#define PARA_SELECTED_DATE          @"selected_date"
#define PARA_RECOMMEND_COURSE_LIST  @"recommend_course_list"
#define PARA_COUNT                  @"count"
#define PARA_CAN_ORDER_COUNT        @"can_order_count"
#define PARA_SMALL_IMAGE_URL        @"small_image_url"
#define PARA_BUSINESSES             @"businesses"
#define PARA_BUSINESS               @"business"
#define PARA_BUSINESS_ID            @"business_id"
#define PARA_NAME                   @"name"
#define PARA_IMAGE_URL              @"image_url"
#define PARA_LINK                   @"link"
#define PARA_GROUP                  @"group"
#define PARA_ICON_URL               @"icon_url"
#define PARA_HAS_MORE_COURSE        @"has_more_course"
#define PARA_SUB_REGION             @"sub_region"
#define PARA_SUB_REGION_NAME        @"sub_region_name"
#define PARA_ADDRESS                @"address"
#define PARA_VENUES_TELEPHONE       @"venues_telephone"
#define PARA_TELEPHONE              @"telephone"
#define PARA_LATITUDE               @"latitude"
#define PARA_LONGITUDE              @"longitude"
#define PARA_QUERY_SUPPORT          @"query_support"
#define PARA_QUERY_DATE             @"query_date"
#define PARA_QUERY_HOUR             @"query_hour"
#define PARA_QUERY_NUMBER           @"query_number"
#define PARA_CAN_ORDER              @"can_order"
#define PARA_OTHER_SERVICE          @"other_service"
#define PARA_OTHER_SERVICE_LIST     @"other_service_list"
#define PARA_CATEGORY_ID_LIST       @"category_id_list"
#define PARA_CHARACTERISTIC_LIST    @"characteristic_list"
#define PARA_PRICE_DESC             @"price_desc"
#define PARA_FACILITIES             @"facilities"
#define PARA_LIST                   @"list"
#define PARA_PHOTO_LIST             @"photo_list"
#define PARA_LISTS                  @"lists"
#define PARA_TRAFFIC_INFO_LIST      @"traffic_info_list"
#define PARA_COURT_JOIN_LIST        @"court_join_list"
#define PARA_COURT_JOIN_DATE_LIST   @"court_join_date_list"
#define PRAR_SEARCH_TEXT            @"search_text"
#define PARA_START_DATE             @"start_date"
#define PARA_END_DATE               @"end_date"
#define PARA_START_HOUR             @"start_hour"
#define PARA_END_HOUR               @"end_hour"
#define PARA_BOOK_LIST              @"book_list"
#define PARA_BOOK_LISTS             @"book_lists"
#define PARA_BOOK_DATE              @"book_date"
#define PARA_COURSE_LIST            @"course_list"
#define PARA_COURSE_ID              @"course_id"
#define PARA_COURSE_NAME            @"course_name"
#define PARA_POSITION_NAME          @"position_name"
#define PARA_ITEMS                  @"items"
#define PARA_COURSE_NUMBER          @"course_number"
#define PARA_HOUR_LIST              @"hour_list"
#define PARA_GOODS_ID               @"goods_id"
#define PARA_GOODS_NAME             @"goods_name" 
#define PARA_GOODS_NUMBER           @"goods_number"
#define PARA_LIMIT_NUMBER           @"limit_number"
#define PARA_HOUR                   @"hour"
#define PARA_PRICE                  @"price"
#define PARA_PROMOTE_PRICE          @"promote_price"
#define PARA_GOODS_IDS              @"goods_ids"
#define PARA_GOODS_LIST             @"goods_list"
#define PARA_FROM                   @"from"
#define PARA_PAYMENT_ID             @"payment_id"
#define PARA_ORDER_ID               @"order_id"
#define PARA_SELECTED_NUMBER        @"number"//1.99添加意愿调查
#define PARA_SHARE_INFO             @"share_info"
#define PARA_ORDER_TYPE             @"order_type"
#define PARA_TOTAL_AMOUNT           @"total_amount"
#define PARA_ORDER_PROMOTE          @"order_promote"
#define PARA_ORDER_PROMOTION        @"order_promote_original"
#define PARA_ORDER_AMOUNT           @"order_amount"
#define PARA_ORDER_NO               @"order_no"
#define PARA_ORDER_SN               @"order_sn"
#define PARA_VERIFICATION_CODE      @"verification_code"
#define PARA_ORDER_STATUS           @"order_status"
#define PARA_ADD_TIME               @"add_time"
#define PARA_SHOP_PRICE             @"shop_price"
#define PARA_COMMENTS               @"comments"
#define PARA_COMMENT_ID             @"comment_id"
#define PARA_COMMENT                @"comment"
#define PARA_CREATE_TIME            @"create_time"
#define PARA_REPLY_COMMENTS         @"reply_comments"
#define PARA_CONTENT                @"content"
#define PARA_COMMENT_RANK           @"comment_rank"
#define PARA_RANK                   @"rank"
#define PARA_COMMENT_AVG            @"comment_avg"
#define PARA_IS_CARD_USER           @"is_card_user"
#define PARA_IMAGE_LIST             @"image_list"
#define PARA_GALLERY_IDS            @"gallery_ids"
#define PARA_IS_READ                @"is_read"
#define PARA_REPLY_COMMENT_ID       @"reply_comment_id"
#define PARA_CITIES                 @"cities"
#define PARA_CITY_ID                @"city_id"
#define PARA_VENUES_ID              @"venues_id"
#define PARA_VENUE_ID               @"venue_id"
#define PARA_CITY_NAME              @"city_name"
#define PARA_CITY_LONGITUDE         @"longitude"
#define PARA_CITY_LATITUDE          @"latitude"
#define PARA_REGIONS                @"regions"
#define PARA_REGION_ID              @"region_id"
#define PARA_REGION_NAME            @"region_name"
#define PARA_SORT                   @"sort"
#define PARA_PAGE                   @"page"
#define PARA_REGISTER               @"register"
#define PARA_BIND                   @"bind"
#define PARA_FORGOT_PASSWROD        @"forgot_password"
#define PARA_TYPE                   @"type"
#define PARA_OTHER_SERVICE_LIST     @"other_service_list"
#define PARA_SERVICE_ID             @"service_id"
#define PARA_SERVICE_NAME           @"service_name"
#define PARA_ALIPAY_NOTIFY_URL      @"alipay_notify_url"
#define PARA_WEIXIN_NOTIFY_URL      @"weixin_notify_url"
#define PARA_ORDER_LIST             @"order_list"
#define PARA_FAVORITE_LIST          @"favorite_list"
#define PARA_OLD_PASSWORD           @"old_password"
#define PARA_NEW_PASSWORD           @"new_password"
#define PARA_COMMENT_COUNT          @"comment_count"
#define PARA_COLLECT_NUMBER         @"collect_number"
#define PARA_GAM_URL                @"gam_url" 
#define PARA_FAVORITE_SPORTS        @"favorite_sports"
#define PARA_ACTIVE_IMAGE_URL       @"active_image_url"
#define PARA_PROJECT                @"project"
#define PARA_ACT_ID                 @"act_id"
#define PARA_PRO_ID                 @"pro_id"
#define PARA_PRO_NAME               @"pro_name"
#define PARA_ACT_NAME               @"act_name"
#define PARA_ACT_COST               @"act_cost"
#define PARA_ACT_COST_TOTAL         @"act_cost_total"
#define PARA_ACT_PEOPLE_NUMBER      @"act_people_number"
#define PARA_IS_VENUES              @"is_venues"
#define PARA_ACT_ADDRESS            @"act_address"
#define PARA_ACT_USER_ID            @"act_user_id"
#define PARA_ACT_TIME               @"act_time"
#define PARA_END_TIME               @"end_time"
#define PARA_GIVE_INTEGRAL          @"give_integral"
#define PARA_INTEGRAL_TYPE          @"integral_type"
#define PARA_INTEGRAL               @"integral"
#define PARA_ACT_DESC               @"act_desc"
#define PARA_MIN_AGE                @"min_age"
#define PARA_MAX_AGE                @"max_age"
#define PARA_SPORT_LEVEL            @"sport_level"
#define PARA_ACTIVITY               @"activity"
#define PARA_PROMISE                @"promise"
#define PARA_CAN_TIME_QUERY         @"can_time_query"
#define PARA_PROMISE_ID             @"promise_id"
#define PARA_PROMISE_USER_ID        @"promise_user_id"
#define PARA_LIKE_LIST              @"like_list"
#define PARA_HOT_IMAGE              @"hot_image"
#define PARA_ADD_SURVEY_SWITCH      @"add_survey_switch"
#define PARA_START_TIME             @"start_time"
#define PARA_TIME_STR               @"time_str"
#define PARA_END_TIME               @"end_time"
#define PARA_USER_INFO              @"user_info"
#define PARA_APPOINTMENT_RATE       @"appointment_rate"
#define PARA_APPOINTMENT_TOTAL      @"appointment_total"
#define PARA_AD_LIST                @"ad_list"
#define PARA_VENUE_LIST             @"venue_list"
#define PARA_USER_LIST              @"user_list"
#define PARA_DATA                   @"data"
#define PARA_AD_ID                  @"ad_id"
#define PARA_AD_NAME                @"ad_name"
#define PARA_AD_LINK                @"ad_link"
#define PARA_INDEX_IMAGE            @"index_image"
#define PARA_PROVINCE_ID            @"province_id"
#define PARA_PROVINCE_NAME          @"province_name"
#define PARA_CITY_LIST              @"city_list"
#define PARA_SIGNATURE              @"signature"
#define PARA_INTERESTED_SPORT       @"interested_sport"
#define PARA_INTERESTED_SPORT_LEVEL @"interested_sport_level"
#define PARA_SPORT_PLAN             @"sport_plan"
#define PARA_USER_CITY_ID           @"user_city_id"
#define PARA_MSG                    @"msg"
#define PARA_RES_MSG                @"resMsg"
#define PARA_THUMB_URL              @"thumb_url"
#define PARA_GALLERY                @"gallery"
#define PARA_EQUIPMENT              @"equipment"
#define PARA_ID                     @"id"
#define PARA_GROUP_ID               @"group_id"
#define PARA_GROUP_TYPE             @"group_type"
#define PARA_GROUP_NAME             @"group_name"
#define PARA_CHAT_COUNT             @"chat_count"
#define PARA_CHAT_LIST              @"chat_list"
#define PARA_MESSAGE                @"message"
#define PARA_FROM_USER_ID           @"from_user_id"
#define PARA_TO_USER_ID             @"to_user_id"
#define PARA_REQUEST_USER_ID        @"request_user_id"
#define PARA_AVATAR_ORIGINAL        @"avatar_original"
#define PARA_PROMOTE_MESSAGE        @"promote_message"
#define PARA_MESSAGE_TYPE           @"message_type"
#define PARA_CONFIG                 @"config"
#define PARA_IOS_INTEGRAL_KEY       @"ios_integral_key"
#define PARA_IOS_PUSH_TOKEN         @"ios_push_token"
#define PARA_REGISTRATION_ID        @"registration_id"
#define PARA_COUPON_ID              @"coupon_id"
#define PARA_COUPON_SN              @"coupon_sn"
#define PARA_COUPON_AMOUNT          @"coupon_amount"
#define PARA_COUPON_NAME            @"coupon_name"
#define PARA_USE_START_DATE         @"use_start_date"
#define PARA_USE_END_DATE           @"use_end_date"
#define PARA_MIN_AMOUNT             @"min_amount"
#define PARA_MAX_AMOUNT             @"max_amount"
#define PARA_DESCRIPTION            @"description"
#define PARA_BOOK_DATE              @"book_date"
#define PARA_GROUP_LIST             @"group_list"
#define PARA_SHOW_COUPON            @"show_coupon"
#define PARA_HELP_URL               @"help_url"
#define PARA_IS_SHARE               @"is_share"
#define PARA_SHARE_MSG              @"share_msg"
#define PARA_IS_OFTEN               @"is_often"
#define PARA_IS_COLLECT             @"is_collect"
#define PARA_IS_SHOW                @"is_show"
#define PARA_OPEN_UNION_ID          @"open_union_id"
#define PARA_MIN_LATITUDE           @"min_latitude"
#define PARA_MAX_LATITUDE           @"max_latitude"
#define PARA_MIN_LONGITUDE          @"min_longitude"
#define PARA_MAX_LONGITUDE          @"max_longitude"
#define PARA_MIN_PRICE              @"min_price"
#define PARA_MAX_PRICE              @"max_price"
#define PARA_START_UP_IMAGE         @"start_up_image"
#define PARA_MONCARD_INTRODUCE_URL  @"moncard_introduce_url"
#define PARA_PAYMENT_METHOD         @"payment_method"
#define PARA_PAYMENT_METHOD_PAYID   @"payment_method_payid"
#define PARA_DEVICE_ID              @"device_id"
#define PARA_DEVICE                 @"device"
#define PARA_COURSE_TYPE            @"course_type"
#define PARA_IOS_APP_VERSION        @"ios_app_version"
#define PARA_UPDATE_PROFILE         @"update_profile"
#define PARA_IS_FORCED              @"is_forced"
#define PARA_LAST_VERSION           @"last_version"
#define PARA_PROMOTE_LIST           @"promote_list"
#define PARA_NOTICE                 @"notice"
#define PARA_IMAGE_COUNT            @"image_count"
#define PARA_MAIN_IMAGE_COUNT       @"main_image_count"
#define PARA_IS_COMMENT             @"is_comment"
#define PARA_ACTIVITY_LIST          @"activity_list"
#define PARA_ACT_AMOUNT             @"act_amount"
#define PARA_ORDER                  @"order"
#define PARA_CONVERT_ID             @"convert_id"
#define PARA_TYPE_ID                @"type_id"
#define PARA_IS_VIRTUAL             @"is_virtual"
#define PARA_COUPON_MONEY           @"coupon_money"
#define PARA_ORIGINAL_CREDIT        @"original_credit"
#define PARA_GIFT_TYPE              @"gift_type"
#define PARA_GIFT_LIST              @"gift_list"
#define PARA_LOTTERY_CREDIT         @"lottery_credit"
#define PARA_GIFT_ID                @"gift_id"
#define PARA_SHORT_DESCRIPTION      @"short_description"
#define PARA_CREDIT_RULE_URL        @"credit_rule_url"
#define PARA_LOTTERY_RULE_URL       @"lottery_rule_url"
#define PARA_PROMOTE_END_DATE       @"promote_end_date"
#define PARA_DETAIL_URL             @"detail_url"
#define PARA_INVITE_CODE            @"invite_code"
#define PARA_CREDIT_DESCRIPTION     @"credit_description"
#define PARA_RECOMMEND_DESCRIPTION  @"recommend_description"
#define PARA_RECOMMEND_REMARK       @"recommend_remark"
#define PARA_COMMENT_DESCRIPTION    @"comment_description"
#define PARA_COUPON_RULE_URL        @"coupon_rule_url"
#define PARA_SURPLUS_COUNT          @"surplus_count"
#define PARA_DATE_LIST              @"date_list"
#define PARA_CURRENT_TIME           @"current_time"
#define PARA_SMS_CODE               @"sms_code"
#define PARA_USER_PROTOCOL_URL      @"user_protocol_url"
#define PARA_CONVERT_TIME           @"convert_time"
#define PARA_IS_SETPASSWORD         @"is_setpassword"
#define PARA_IS_SET_PAYPASSWORD     @"is_set_paypassword"
#define PARA_IS_REFUND              @"is_refund"
#define PARA_REFUND_STATUS          @"refund_status"
#define PARA_REFUND_AMOUNT          @"refund_amount"
#define PARA_REFUND_WAY             @"refund_way"
#define PARA_REFUND_NUM             @"refund_num"
#define PARA_TITLE                  @"title"
#define PARA_REFUND_CAUSE           @"refund_cause"
#define PARA_IS_PAYPASSWORD         @"is_paypassword"
#define PARA_USER_MONEY             @"user_money"
#define PARA_USER_CLUB_STATUS       @"user_club_status"
#define PARA_USABLE_DAYS            @"usable_days"
#define PARA_REFUND_RULE_URL        @"refund_rule_url"
#define PARA_USER_MONEY_RULE_URL    @"user_money_rule_url"
#define PARA_USER_CARD_URL          @"user_card_url"
#define PARA_MONEY                  @"money"
#define PARA_TRANSIT_INFO           @"transit_info"
#define PARA_METRO_INFO             @"metro_info"
#define PARA_ACTIVITY_MESSAGE       @"activity_message"
#define PARA_ALIPAY_KEYWORD         @"alipay_keyword"
#define PARA_WAP_PAY_SUCCESS_TITLE  @"wap_pay_success_title"
#define PARA_WAP_PAY_FAIL_TITLE     @"wap_pay_fail_title"
#define PARA_CARD_NO                @"card_no" 
#define PARA_CARD_MOBILE_PHONE      @"card_mobile_phone"
#define PARA_CARD_MOBILE_ENCODE     @"card_mobile_encode"
#define PARA_VENUES_ID              @"venues_id"
#define PARA_MOBILE                 @"mobile"
#define PARA_CAT_ID                 @"cat_id"
#define PARA_BALANCE                @"balance"
#define PARA_CARD_STATUS            @"card_status"
#define PARA_CHECKBIND              @"checkbind"
#define PARA_BIND_BY_OTHER          @"bind_by_other"
#define PARA_BIND_BY_PHONE          @"bind_by_phone"
#define PARA_IS_SET_PAY_PASSWORD    @"is_set_paypassword"
#define PARA_PAY_PASSWORD           @"pay_password"
#define PARA_PAY_ID                 @"pay_id"
#define PARA_USE_WALLET             @"use_wallet"
#define PARA_REFUND_MESSAGE         @"refund_message"
#define PARA_USER_BALANCE           @"user_balance"
#define PARA_USER_CARD_INFO         @"user_card_info"
#define PARA_CARDHOLDER             @"cardholder"
#define PARA_AMOUNT                 @"amount"
#define PARA_GIFT_AMOUNT            @"gift_amount"
#define PARA_USERHOLDER             @"userholder"
#define PARA_OLD_PAY_PASSWORD       @"pay_old_password"
#define PARA_NEW_PAY_PASSWORD       @"pay_new_password"
#define PARA_SMS_CODE_LENGTH        @"length"
#define PARA_SERVICE_LIST           @"service_list"
#define PARA_FACILITY_LIST_IMAGE    @"facility_list_image"
#define PARA_ICON_URL               @"icon_url"
#define PARA_LAST_REFUND_TIME       @"last_refund_time"
#define PARA_IMAGE_TITLE            @"img_title"
#define PARA_IMAGE_DESC             @"img_desc"

#define PARA_COTERIE                @"coterie"
#define PARA_COTERIE_ID             @"coterie_id"
#define PARA_COTERIE_NAME           @"coterie_name"
#define PARA_COTERIE_COVER_IMG      @"coterie_cover_img"
#define PARA_POST                   @"post"
#define PARA_POST_ID                @"post_id"
#define PARA_POST_CONTENT           @"post_content"
#define PARA_USER_AVATAR            @"user_avatar"
#define PARA_USER_NAME              @"user_name"
#define PARA_LAST_UPDATE_TIME       @"last_update_time"
#define PARA_ATTACH_LIST            @"attach_list"
#define PARA_URL                    @"url"
#define PARA_COVER_IMG              @"cover_img"
#define PARA_CURRENT_POST_COUNT     @"current_post_count"
#define PARA_POST_COUNT             @"post_count"
#define PARA_OFTEN_GO_TO            @"often_go_to"
#define PARA_FORUM_SEARCH_DATA_VER  @"forum_search_data_ver"
#define PARA_COM_ID                 @"com_id"
#define PARA_COM_CONTENT            @"com_content"
#define PARA_ATTACH_IDS             @"attach_ids"
#define PARA_ATTACH_ID              @"attach_id"
#define PARA_BEEN_COTERIE           @"been_coterie"
#define PARA_USER_POST_COUNT        @"user_post_count"
#define PARA_FROM_USER_ID           @"from_user_id"
#define PARA_TO_USER_ID             @"to_user_id"
#define PARA_HAS_ATTACH             @"has_attach"
#define PARA_THUMB_URL              @"thumb_url"
#define PARA_FROM_USER_NAME         @"from_user_name"
#define PARA_FROM_USER_AVATAR       @"from_user_avatar"

//CourtPool
#define PARA_COURT_POOL_STATUS       @"court_pool_status"
#define PARA_CURRENT_NUM             @"current_num"
#define PARA_COURT_POOL_ID           @"court_pool_id"
#define PARA_FULL_PLAYERS_NUM        @"full_players_num"
#define PARA_START_PLAYERS_NUM       @"start_players_num"
#define PARA_QUESTION                @"question"
//拼场1.0
#define PARA_COURT_POOL_MAG_1        @"court_pool_msg_1"
#define PARA_COURT_POOL_MAG_2        @"court_pool_msg_2"
//拼场2.0
#define PARA_CP_MSG_1                @"cp_msg_1"
#define PARA_CP_MSG_2                @"cp_msg_2"
#define PARA_JOIN_TIMES              @"join_times"
#define PARA_WITH_TIMES              @"with_times"
#define PARA_COURT_NO                @"court_no"

//MonthCard
#define PARA_IS_SUPPORT_CLUB        @"is_support_club"
#define PARA_VENUES_ID              @"venues_id"
#define PARA_VENUES_NAME            @"venues_name"
#define PARA_LOCATION_NAME          @"location_name"
#define PARA_VENUES_ADDRESS          @"venues_address"
#define PARA_IS_RECOMMEND           @"is_recommend"
#define PARA_TIME                   @"time"
#define PARA_CATEGORY_LIST          @"category_list"
#define PARA_IMG_URL                @"img_url"
#define PARA_MONCARD_CATEGORIES     @"moncard_categories"
#define PARA_SIGN                   @"sign"
#define PARA_CARD_ID                @"card_id"
#define PARA_THUMB_AVATAR           @"thumb_avatar"
#define PARA_BUSINESS_DATE          @"date"
#define PARA_COURSE_URL             @"moncard_course_url"
#define PARA_DATE                   @"date"
#define PARA_CATEGORY_IMG_URL       @"category_img_url"
#define PARA_COURSE_START_TIME      @"course_start_time"
#define PARA_COURSE_END_TIME        @"course_end_time"
#define PARA_MONCARD_INDEX_URL      @"moncard_index_url"
#define PARA_MONCARD_COURSE_URL     @"moncard_course_url"
#define PARA_MONCARD_HELP_URL       @"moncard_help_url"
#define PARA_MONCARD_STATUS         @"moncard_status"
#define PARA_SHARE_URL              @"share_url"

#define PARA_LOGO_URL              @"logo_url"
#define PARA_MONCARD_NOTICE         @"moncard_notice"
#define PARA_IS_SUPPORT_CLUB         @"is_support_club"

#define PARA_SN                     @"sn"
#define PARA_TICKET_TYPE            @"ticket_type"
#define PARA_IS_ENABLE              @"is_enable"
#define PARA_IS_ENABLE              @"is_enable"
#define PARA_DISABLE_MSG            @"disable_msg"

#define PARA_TICKET_ID              @"ticket_id"
#define PARA_TICKET_NO              @"ticket_no"

#define PARA_COACH_RECRUIT_URL      @"coach_recruit_url"
#define PARA_COACH_ID               @"coach_id"
#define PARA_COACH_IMG              @"coach_img"
#define PARA_COACH_NAME             @"coach_name"
#define PARA_COACH_AVATAR           @"coach_avatar"
#define PARA_COACH_IS_AUDIT         @"coach_is_audit"
#define PARA_COACH_GENDER           @"coach_gender"
#define PARA_SHOW_STATUS            @"show_status"
#define PARA_IS_CAN_CANCEL          @"is_can_cancel"
#define PARA_COACH_PHONE            @"coach_phone"
#define PARA_COACH_AGE              @"coach_age"
#define PARA_COACH_HEIGHT           @"coach_height"
#define PARA_COACH_WEIGHT           @"coach_weight"
#define PARA_DURATION               @"duration"
#define PARA_CATEGORY               @"category"
#define PARA_CAT_NAME               @"cat_name"
#define PARA_IMAGES                 @"images"
#define PARA_AGE                    @"age"
#define PARA_WEIGHT                 @"weight"
#define PARA_HEIGHT                 @"height"
#define PARA_COACH_RONG_ID          @"c_uid"
#define PARA_USER_RONG_ID           @"rc_uid"
#define PARA_OFTEN_AREA             @"often_area"
#define PARA_MORNING                @"morning"
#define PARA_AFTERNOON              @"afternoon"
#define PARA_NIGHT                  @"night"
#define PARA_CATEGORY_PRICE         @"category_price"
#define PARA_REASON_ID              @"reason_id"
#define PARA_REASON_DESC            @"reason_desc"
#define PARA_IM_TOKEN               @"im_token"
#define PARA_REFRESH                @"refresh"
#define PARA_TOKEN                  @"token"
#define PARA_TIME_RANGE             @"time_range"
#define PARA_USER_PHONE             @"user_phone"
#define PARA_INTRODUCE              @"introduce"
#define PARA_STUDENT_COUNT          @"student_count"
#define PARA_TOTOAL_TIME            @"totoal_time"
#define PARA_COMMENT_AVG            @"comment_avg"
#define PARA_SERVICE_AREA_LIST      @"service_area_list"
#define PARA_COMMENT_LIST           @"comment_list"
#define PARA_GRAY_IMG               @"gray_img"
#define PARA_ACTIVE_IMG             @"active_img"
#define PARA_COMMENT_STATUS         @"comment_status"
#define PARA_COMPLAIN_STATUS        @"complain_status"
#define PARA_CANCEL_ORDER_MSG       @"cancel_order_msg"
#define PARA_GROUP_BUY_URL          @"group_buy_url"
#define PARA_IOS_IN_REVIEW_VERSION  @"ios_in_review_version"
#define PARA_COACH_OPEN_CITY_IDS    @"coach_open_city_ids"
#define PARA_IS_SUPPORT_CLUB        @"is_support_club"
#define PARA_IDLE_VENUE             @"idle_venue"
#define PARA_REFUND_TIPS            @"refund_tips"
#define PARA_USER_CLUB_STATUS       @"user_club_status"
#define PARA_CLUB_DISABLE_MSG       @"club_disable_msg"
#define PARA_NO_BUY_CLUB_MSG        @"no_buy_club_msg"
#define PARA_USE_CLUB_PAY           @"use_club_pay"
#define PARA_HAS_NOUSED_CLUB_MSG    @"has_noused_club_msg"
#define PARA_ORDER_NAME             @"order_name"
#define PARA_SHARE_BTN_MSG          @"share_btn_msg"
#define PARA_CLUB_END_TIME          @"club_end_time"
#define PARA_COACH_IN_REVIEW_URL    @"ios_coach_in_review_url"
#define PARA_MIN_HOUR               @"min_hour"
#define PARA_ORDER_TITLE            @"order_title"
#define PARA_ORDER_ICON             @"order_icon"
#define PARA_FIELD_NO               @"field_no"
#define PARA_TIPS                   @"tips"
#define PARA_GET_PAY_ID             @"get_pay_id"
#define PARA_SHARE_TO               @"share_to"
#define PARA_PAYMENT_METHOD_PAYID_V2   @"payment_method_payid_v2"
#define PARA_SPORT_EXPERIENCE       @"sport_experience"
#define PARA_COACH_PROJECTS         @"coach_projects"
#define PARA_EXPERIENCE_CONTENT     @"experience_content"
#define PARA_PROJECT_NAME           @"project_name"
#define PARA_ROLE_ID                @"role_id"
#define PARA_MINUTES                @"minutes"
#define PARA_LEVEL                  @"level"
#define PARA_LEVEL_DESC             @"level_desc"
#define PARA_OFTEN_AREA_LIST        @"often_area_list"
#define PARA_TYPE_ICON              @"type_icon"
#define PARA_TYPE_NAME              @"type_name"
#define PARA_FLAG                   @"flag"
#define PARA_NUMS                   @"nums"
#define PARA_NUM                    @"num"
#define PARA_SEND_TIME              @"send_time"
#define PARA_IMG                    @"img"
#define PARA_EXTRA                  @"extra"
#define PARA_FROM_USER              @"from_user"
#define PARA_MONTH_REFUND_TIMES     @"month_refund_times"
#define PARA_CARD_SUPPORT           @"card_support"
#define PARA_USER_CARD_LIST         @"user_card_list"
#define PARA_CARD_BALANCE           @"card_balance"
#define PARA_COURT_ID               @"court_id"
#define PARA_COURT_NAME             @"court_name"
#define PARA_COURT_NUMBER           @"court_number"
#define PARA_NMQ_URL                @"nmq_url"
#define PARA_FRONT_VOLUME_NAME      @"front_volume_name"
#define PARA_FIRST_INSTRUCTION      @"first_instruction"
#define PARA_SECOND_INSTRUCTION     @"second_instruction"
#define PARA_THIRD_INSTRUCTION      @"third_instruction"
#define PARA_FRONT_TICKET_NAME      @"front_ticket_name"
#define PARA_FRONT_COUPON_NAME      @"front_coupon_name"
#define PARA_MSG_TYPE               @"msg_type"
#define PARA_COACH_REFUND           @"coach_refund"
#define PARA_COURT_POOL_ID          @"court_pool_id"
#define PARA_COURT_POOLS            @"court_pools"
#define PARA_MIN_NUM                @"min_num"
#define PARA_MAX_NUM                @"max_num"
#define PARA_JOIN_STATUS            @"join_status"
#define PARA_TEXT                   @"text"
#define PARA_COURT_POOL_TIPS        @"court_pool_tips"
#define PARA_SHARE                  @"share"
#define PARA_LOGO                   @"logo"
#define PARA_LEVEL_NAME             @"level_name"
#define PARA_IS_PARK                @"is_park"
#define PARA_PARK_LIST              @"park_list"
#define PARA_PARK_TAGS              @"tags"
#define PARA_DATE_TIME              @"date_time"

//Insurance
#define PARA_INSURANCE_CONTENT      @"insurance_content"
#define PARA_INSURANCE_URL          @"insurance_url"
#define PARA_INSURANCE_PAY_TIPS     @"insurance_pay_tips"
#define PARA_INSURANCE              @"insurance"
#define PARA_INSURANCE_SWITCH       @"insurance_switch"
#define PARA_INSURANCE_ID           @"insurance_id"
#define PARA_INSURANCE_NAME         @"insurance_name"
#define PARA_INSURANCE_UNIT_PRICE   @"insurance_unit_price"
#define PARA_INSURANCE_TIPS         @"insurance_tips"
#define PARA_INSURANCE_INTRODUCTION @"insurance_introduction"
#define PARA_INSURANCE_QUANTITY     @"insurance_quantity"
#define PARA_INSURANCE_ORDER_TIME   @"insurance_order_time"
#define PARA_INSURANCE_LIMIT_TIPS   @"insurance_limit_tips"

//1.97
#define PARA_JOIN_END_TIME           @"join_end_time"
#define PARA_LEVELS                  @"levels"
#define PARA_LEVEL_ID                @"level_id"
#define PARA_JOIN_TIMES              @"join_times"
#define PARA_WITH_TIMES              @"with_times"
#define PARA_JOIN_TIPS               @"join_tips"
#define PARA_CP_LEVEL                @"cp_level"
#define PARA_TOTAL                   @"total"
#define PARA_COMPLETE                @"complete"
#define PARA_LAST_NUM                @"last_num"

//1.98
#define PARA_PAY_EXPIRE_LEFT        @"pay_expire_left"

//1.991
#define PARA_PAY_TOKEN              @"pay_token"

#define PARA_VALUE                  @"value"
#define PARA_EXPIRES                @"expires"
#define PARA_QYD_TOKEN              @"qyd_token"

//2.0.0
#define PARA_SERVER_TIME            @"server_time"
#define PARA_UPDATE_RESULT          @"updateRes"
#define PARA_COURT_USER_ID          @"launch_user_id"
#define PARA_COURT_USER_NICK_NAME   @"launch_nick_name"
#define PARA_COURT_USER_AVATAR      @"launch_avatar"
#define PARA_LAUNCH_MOBILE          @"launch_mobile"
#define PARA_BUSINESS_NAME          @"business_name"
#define PARA_BUSINESS_ADDRESS       @"business_address"
#define PARA_SIGN_IN_ID             @"si_id"
#define PARA_SIGN_IN                @"sign_in"
#define PARA_DAY_SIGNIN_STATUS      @"day_signin_status"
#define PARA_FOUR_WEEK_SIGNIN       @"four_week_signin"
#define PARA_VERSION_SIGN_IN_STATUS @"sign_in_status"
#define PARA_WEEK_SIGNIN_TIMES      @"week_signin_times"
#define PARA_WEEK_NAME              @"week_name"
#define PARA_PLAYERS_NUM            @"players_num"
#define PARA_CJ_ORDER_ID            @"cj_order_id"
#define PARA_NEARBY_VENUES          @"near_venues"
#define PARA_SIGN_IN_TIME           @"sign_in_time"
#define PARA_INTEGRAL_TIPS          @"integral_tips"
#define PARA_WEEK_TIPS              @"week_tips"
#define PARA_SHARE_TITLE            @"share_title"
#define PARA_SHARE_CONTENT          @"share_content"
#define PARA_DIARY                  @"diary"
#define PARA_TEN_WEEK_DATA          @"ten_week_data"
#define PARA_WISDOM                 @"wisdom"
#define PARA_AUTHOR                 @"author"

#define PARA_SIGN_IN_STATUS         @"signin_status"
#define PARA_COUPON                 @"coupon"
#define PARA_WEEK_NAME              @"week_name"
#define PARA_SHARE_COURT_JOIN_URL   @"share_cj_url"
#define PARA_COURT_JOIN_INFO        @"court_join_info"
#define PARA_ALREADY_JOIN_NUM       @"already_join_num"
#define PARA_PARTICIPANT_INFO       @"participant_info"
#define PARA_IS_FIRST_TIME_SPONSOR  @"user_first"
#define PARA_VENUES_INFO            @"venues_info"
#define PARA_PERIOD_TIME            @"period_time"
#define PARA_PARENT_ORDER_ID        @"parent_order_id"
#define PARA_FIELD_GOODS_LIST       @"field_goods_list"
#define PARA_PRICE_TAG_MSG          @"price_tag_msg"
#define PARA_COURT_JOIN_PERMISSION  @"court_join_permission"
#define PARA_COURT_JOIN_MSG         @"court_join_msg"
#define PARA_COURT_JOIN_SHARE_INFO  @"court_join_share_info"
#define PARA_COURT_JOIN_DESCRIPTION @"court_join_description"
#define PARA_COURT_JOIN_STATUS      @"court_join_status"
#define PARA_COURT_JOIN_STATUS_MSG  @"court_join_status_msg"
#define PARA_LEFT_JOIN_NUM_MSG          @"left_join_num_msg"
#define PARA_COURT_JOIN_REMIND_TIPS @"court_join_remind_tips"
#define PARA_COURT_JOIN_AVAILABLE   @"court_join_available"
#define PARA_COURT_JOIN_DISABLE_MSG @"court_join_disable_msg"
#define PARA_COURT_JOIN_GOODS_LIST  @"court_join_goods_list"
#define PARA_IS_COURT_JOIN_PARENT   @"court_join_parent"

#define PARA_IS_CHECK_NEW_VERSION   @"is_check_new_version"
#define PARA_IS_SHOW_THIRD_PARTY_LOGIN  @"is_show_third_party_login"
#define PARA_LINKS_MODULES          @"links_modules"
#define PARA_KEYWORD_MODULES        @"keyword_modules"
#define PARA_SIGNIN_RULE_URL                @"signin_rule_url"
#define PARA_COURT_JOIN_INSTRUCTION_URL   @"court_join_instruction_url"
#define PARA_CASH_MONEY             @"cash_money"
#define PARA_ORDER_MONEY            @"order_money"
#define PARA_COURT_JOIN_PRICE       @"court_join_price"
#define PARA_TICKET_LIST            @"ticket_list"
#define PARA_EXPIRE_TICKET_LIST     @"expire_ticket_list"
#define PARA_EXPIRE_COUPON_LIST     @"expire_coupon_list"
#define PARA_ORDER_INFO             @"order_info"
#define PARA_PAGE_DATA              @"page_data"
#define PARA_TOTAL_NUM              @"total_num"
#define PARA_RECORD_TITLE           @"record_title"
#define PARA_RECORD_TOTAL           @"record_total"

//2.1.0
#define PARA_TICKET_NUM             @"ticket_num"
#define PARA_RECEIVE_GUIDE          @"receive_guide"
#define PARA_LIMIT_BUY              @"limit_buy"
#define PARA_SPECI                  @"speci"
#define PARA_SALE_LIST              @"sale_list"
#define PARA_QR_CODE_LIST           @"qr_code_list"
#define PARA_QR_CODE                @"qr_code"
#define PARA_QR_STATUS              @"qr_status"
#define PARA_QR_TIME                @"qr_time"
#define PARA_CARD_AMOUNT            @"card_amount"
#define PARA_OWNER_MOBILE             @"owner_mobile"
#define PARA_OWNER_MOBILE_ENCODE     @"owner_mobile_encode"
#define PARA_USEFUL                 @"useful_use"
#define PARA_USEFUL_COUNT           @"useful_num"
#define PARA_REPLY_LIST             @"reply_list"
#define PARA_REPLY_REMARK           @"reply_remark"
#define PARA_IS_USEFUL              @"is_useful"
#define PARA_NAV_ID                 @"nav_id"
#define PARA_NAVIGATION             @"navigation"
#define PARA_VENUES_CAT_ID          @"venues_cat_id"
#define PARA_MISTAKE_CONTENT        @"mistake_content"
#define PARA_CAN_REFUND_NUM         @"can_refund_num"
#define PARA_PRICE_LIST            @"price_list"
#define PARA_MISTAKE_TYPE           @"mistake_type"
#define PARA_FORMAT_PAY_NAME        @"format_pay_name"
#define PARA_TOTAL_RANK             @"total_rank"
#define PARA_ENTRANCE               @"entrance"
//**************** value *******************
#define VALUE_ACTION_GET_VERIFICATION   @"get_verification"
#define VALUE_ACTION_PHONE_REGISTER     @"phone_register"
#define VALUE_ACTION_UNION_LOGIN        @"union_login"
#define VALUE_ACTION_LOGIN              @"login"
#define VALUE_ACTION_LOGOUT             @"logout"
#define VALUE_ACTION_MY_HOME            @"my_home"
#define VALUE_ACTION_UPDATE_USER_INFO   @"update_user_info"
#define VALUE_ACTION_CATEGORIES         @"categories"
//#define VALUE_ACTION_BUINESSES          @"businesses"
#define VALUE_ACTION_GET_BUINESSES      @"get_businesses"
#define VALUE_ACTION_SEARCH_BUSINESSES  @"search_businesses"
#define VALUE_ACTION_GET_BUSINESS_INFO  @"get_business_info"
#define VALUE_ACTION_GET_BOOKING_SUM    @"get_booking_sum"
#define VALUE_ACTION_GET_VENUE_BOOKING_DATE @"get_venue_booking_date"
#define VALUE_ACTION_UPLOAD_AVATAR      @"upload_avatar"
#define VALUE_ACTION_INSERT_ORDER       @"insert_order"
#define VALUE_ACTION_GET_COMMENTS       @"get_comments"
#define VALUE_ACTION_COMMENT            @"comment"
#define VALUE_ACTION_CITIES             @"cities"
#define VALUE_ACTION_ADD_FAVORITE       @"add_favorite"
#define VALUE_ACTION_REMOVE_FAVORITE    @"remove_favorite"
#define VALUE_ACTION_FAVORITE_LIST      @"favorite_list"
#define VALUE_ACTION_BIND_PHONE         @"bind_phone"
#define VALUE_ACTION_UPDATE_PASSWORD    @"update_password"
#define VALUE_ACTION_UNION_BIND         @"union_bind"
#define VALUE_ACTION_UNION_PHONE        @"union_phone"
#define VALUE_ACTION_RESET_PASSWORD     @"reset_password"
#define VALUE_ACTION_OTHER_SERVICE_LIST @"other_service_list"
#define VALUE_ACTION_GET_ORDER_INFO     @"get_order_info"
#define VALUE_ACTION_ORDER_GET_ORDER_LIST  @"order_get_order_list"
#define VALUE_ACTION_GET_ORDER_LIST     @"get_order_list"
#define VALUE_ACTION_CANCEL_ORDER       @"cancel_order"
#define VALUE_ACTION_INSERT_FEEDBACK    @"insert_feedback"
#define VALUE_ACTION_GET_PROFILE_INFO   @"get_profile_info"
#define VALUE_ACTION_GET_COMMENT_COUNT  @"get_comment_count"
#define VALUE_ACTION_UPDATE_COMMENT_STATUS   @"update_comment_status"
#define VALUE_ACTION_GET_MY_COMMENTS    @"get_my_comments"
#define VALUE_ACTION_ADD_CALL_BOOKING   @"add_call_booking"
#define VALUE_ACTION_GET_CIRCLE_PROJECT @"get_circle_project"
#define VALUE_ACTION_ADD_ACTIVITY       @"add_activity"
#define VALUE_ACTION_GET_ACTIVITY_LIST  @"get_activity_list"
#define VALUE_ACTION_GET_ACTIVITY_INFO  @"get_activity_info"
#define VALUE_ACTION_ADD_PROMISE        @"add_promise"
#define VALUE_ACTION_UPDATE_PROMISE_STATUS  @"update_promise_status"
#define VALUE_ACTION_UPDATE_ACTIVITY_STATUS @"update_activity_status"
#define VALUE_ACTION_GET_USER_LIST          @"get_user_list"
#define VALUE_ACTION_GET_INDEX              @"get_index"
#define VALUE_ACTION_ENTRY_PROJECT_LIST     @"entry_project_list"
#define VALUE_ACTION_GET_INDEX_VENUE_LIST   @"get_index_venue_list"
#define VALUE_ACTION_GET_INDEX_USER         @"get_index_user"
#define VALUE_ACTION_GET_CITY_LIST          @"get_city_list"
#define VALUE_ACTION_CANCEL_PROMISE         @"cancel_promise"
#define VALUE_ACTION_UPLOAD_USER_GALLERY    @"upload_user_gallery"
#define VALUE_ACTION_DELETE_USER_GALLERY    @"delete_user_gallery"
#define VALUE_ACTION_GET_GROUP_CHAT_LIST    @"get_group_chat_list"
#define VALUE_ACTION_GET_CHAT_LIST          @"get_chat_list"
#define VALUE_ACTION_SEND_MESSAGE           @"send_message"
#define VALUE_ACTION_GET_GROUP_ID           @"get_group_id"
#define VALUE_ACTION_GET_ORDER_PROMOTE      @"get_order_promote"
#define VALUE_ACTION_GET_SYSTEM_MESSAGE         @"get_system_message"
#define VALUE_ACTION_GET_SYSTEM_MESSAGE_LIST    @"get_system_message_list"
#define VALUE_ACTION_CHECK_DEPOSIT_INTEGRAL     @"check_deposit_integral"
#define VALUE_ACTION_UPDATE_PUSH_TOKEN          @"update_push_token"
#define VALUE_ACTION_GET_COUPON_LIST            @"get_coupon_list"
#define VALUE_ACTION_ACTIVATE_COUPONT           @"activate_coupon"
#define VALUE_ACTION_BIND_COUPON                @"bind_coupon"
#define VALUE_ACTION_GET_ORDER_AMOUNT           @"get_order_amount"
#define VALUE_ACTION_GET_ORDER_DUE_COUNT        @"get_order_due_count"
#define VALUE_ACTION_SEND_COUPON                @"send_coupon"
#define VALUE_ACTION_GET_MAP_BUSINESS_LIST      @"get_map_business_list"
#define VALUE_ACTION_GET_STATIC_DATA            @"get_static_data"
#define VALUE_ACTION_GET_BUSINESSE_GALLERY      @"get_businesse_gallery"
#define VALUE_ACTION_GET_BUSINESSE_ALL_PHOTO    @"get_business_all_photo"
#define VALUE_ACTION_GET_NEARBY_VENUES          @"get_nearby_venues"
#define VALUE_ACTION_GET_BUSINESS_LIST          @"get_business_park_list"
#define VALUE_ACTION_SUBMIT_VENUES_USER_RECOMMEND  @"submit_venues_user_recommend"
#define VALUE_ACTION_GET_MESSAGE_COUNT_LIST     @"get_message_count_list"
#define VALUE_ACTION_UPDATE_MESSAGE_COUNT       @"update_message_count"
#define VALUE_ACTION_ADD_SHARE_PHONE            @"add_share_phone"
#define VALUE_ACTION_GET_GIFT_LIST              @"get_gift_list"
#define VALUE_ACTION_CONVERT_GIFT               @"convert_gift"
#define VALUE_ACTION_LUCKY_DRAW                 @"lucky_draw"
#define VALUE_ACTION_GET_LUCKY_TOP20            @"get_lucky_top20"
#define VALUE_ACTION_GET_LUCKY_LIST             @"get_lucky_list"
#define VALUE_ACTION_GET_USER_CREDIT_LIST       @"get_user_credit_list"
#define VALUE_ACTION_GET_SALE_LIST              @"get_sale_list"
#define VALUE_ACTION_CHECK_ACTIVITY_INVITE_CODE @"check_activity_invite_code"
#define VALUE_ACTION_GET_SALE_INFO              @"get_sale_info"
#define VALUE_ACTION_CONFIRM_ORDER              @"confirm_order"
#define VALUE_ACTION_GET_SMS_CODE               @"get_sms_code"
#define VALUE_ACTION_QUICK_LOGIN                @"quick_login"
#define VALUE_ACTION_SET_PASSWORD               @"set_password"
#define VALUE_ACTION_CHECK_ORDER_REFUND         @"check_order_refund"
#define VALUE_ACTION_GET_REFUND_STATUS          @"get_refund_status"
#define VALUE_ACTION_APPLY_REFUND               @"apply_refund"
#define VALUE_ACTION_GET_USER_MONEY_LOG         @"get_user_money_log"
#define	VALUE_ACTION_SCAN_CARD                  @"scan_card"
#define	VALUE_ACTION_SCAN_CARD_LOGINED          @"scan_card_logined"
#define	VALUE_ACTION_CARD_LOGIN                 @"card_login"
#define	VALUE_ACTION_GET_CARD_LIST              @"get_card_list"
#define	VALUE_ACTION_GET_CARD_DETAIL            @"get_card_detail"
#define	VALUE_ACTION_CARD_BIND                  @"card_bind"
#define	VALUE_ACTION_CARD_UNBIND                @"card_unbind"
#define	VALUE_ACTION_CARD_RECORD                @"card_record"
#define	VALUE_ACTION_CARD_CONSUME               @"card_consume"
#define	VALUE_ACTION_ADD_USER_CARD_ORDER        @"add_user_card_order"
#define	VALUE_ACTION_GET_USER_CARD_GOODS_LIST   @"get_user_card_goods_list"
#define	VALUE_ACTION_PAY_REQUEST                @"pay_request"
#define	VALUE_ACTION_USER_CARD_PAY              @"user_card_pay"
#define	VALUE_ACTION_APPLY_USER_CARD_REFUND     @"apply_user_card_refund"
#define	VALUE_ACTION_UPDATE_PAY_PASSWORD		@"update_pay_password"
#define	VALUE_ACTION_RESET_PAY_PASSWORD         @"reset_pay_password"
#define VALUE_ACTION_SET_PAY_PASSWORD           @"set_pay_password"
#define VALUE_ACTION_VERIFY_PAY_PASSWORD        @"verify_pay_password"
#define VALUE_ACTION_VERIFY_SMS_CODE            @"verify_sms_code"

#define VALUE_ACTION_GET_POST_LIST              @"get_post_list"
#define VALUE_ACTION_POST_DETAIL                @"post_detail"
#define VALUE_ACTION_ADD_POST                   @"add_post"
#define VALUE_ACTION_GET_COTERIE_LIST           @"get_coterie_list"
#define VALUE_ACTION_COMMENT_LIST               @"comment_list"
#define VALUE_ACTION_ADD_COMMENT                @"add_comment"
#define VALUE_ACTION_SEARCH_STATIC_DATA         @"search_static_data"
#define VALUE_ACTION_POST_IMAGE                 @"post_image"
#define VALUE_ACTION_DEL_IMAGE                  @"del_image"
#define VALUE_ACTION_GET_USER_INFO              @"get_user_info"
#define VALUE_ACTION_HOT_TOPIC                  @"hot_topic"
#define VALUE_ACTION_COMMENT_MESSAGE_LIST       @"get_comment_message_list"

#define VALUE_ACTION_VENUES_LIST                @"venues_list"
#define VALUE_ACTION_COURSE_LIST                @"course_list"
#define VALUE_ACTION_VENUES_INFO                @"venues_info"
#define VALUE_ACTION_RECOMMEND_COURSE           @"recommend_course"
#define VALUE_ACTION_UPLOAD_IMAGE               @"upload_image"
#define VALUE_ACTION_QR_CODE_SIGN               @"qr_code_sign"
#define VALUE_ACTION_CARD_INFO                  @"card_info"
#define VALUE_ACTION_ADD_MON_CARD_ORDER         @"add_mon_card_order"
#define VALUE_ACTION_COURSE_INFO                @"course_info"
#define VALUE_ACTION_BOOK_COURSE                @"book_course"
#define VALUE_ACTION_CHECK_COURSE_STATUS        @"check_course_status"
#define VALUE_ACTION_CARD_GOODS_INFO            @"card_goods_info"
#define VALUE_ACTION_MON_CARD_CONFIRM_ORDER     @"mon_card_confirm_order"
#define VALUE_ACTION_SPORT_ASSISTANT            @"sport_assistant"
#define VALUE_ACTION_SPORT_RECORD_VENUES        @"sport_record_venues"
#define VALUE_ACTION_SPORT_RECORD_COURSE        @"sport_record_course"

#define VALUE_ACTION_RECHARGE_DEBIT_CARD        @"recharge_debit_card"
#define VALUE_ACTION_EXPIRE_TICKET_LIST         @"expire_ticket_list"
#define VALUE_ACTION_GET_TICKET_LIST            @"get_ticket_list"
#define VALUE_ACTION_USER_BALANCE               @"user_balance"
#define VALUE_ACTION_USER_INTEGRAL              @"user_integral"


#define VALUE_ACTION_GET_COACH_LIST             @"get_coach_list"
#define VALUE_ACTION_GET_COACH_ORDER_LIST       @"get_coach_order_list"
#define VALUE_ACTION_GET_COACH_ORDER_INFO       @"get_coach_order_info"
#define VALUE_ACTION_ADD_COACH_COMMENT          @"add_coach_comment"
#define VALUE_ACTION_GET_COACH_INFO             @"get_coach_info"
#define VALUE_ACTION_USER_COLLECTION_COACH      @"user_collection_coach"
#define VALUE_ACTION_GET_BESPEAK_TIME           @"get_bespeak_time"
#define VALUE_ACTION_CANCEL_BESPEAK             @"cancel_bespeak"
#define VALUE_ACTION_CANCEL_CAUSE               @"cancel_cause"
#define VALUE_ACTION_CONFIRM_SERVICE            @"confirm_service"
#define VALUE_ACTION_RONGIM_AVATAR_INFO         @"get_avatar_info"
#define VALUE_ACTION_GET_IM_TOKEN               @"get_im_token"
#define VALUE_ACTION_COACH_CONFIRM_ORDER        @"coach_confirm_order"
#define VALUE_ACTION_ADD_COACH_ORDER            @"add_coach_order"
#define VALUE_ACTION_ADD_COACH_COMPLAIN         @"add_coach_complain"
#define VALUE_ACTION_GET_COACH_COMMENT_LIST     @"get_coach_comment_list"
#define VALUE_ACTION_GET_COACH_CATEGORY         @"get_coach_category"
#define VALUE_ACTION_COMMON_UPLOAD_IMAGE        @"common_upload_image"
#define VALUE_ACTION_COMMON_DELETE_IMAGE        @"common_delete_image"
#define VALUE_ACTION_GET_NOW_TIME               @"get_now_time"
#define VALUE_ACTION_CANCEL_CLUB_ORDER          @"cancel_club_order"
#define VALUE_ACTION_MY_COLLECTING_COACH        @"my_collecting_coach"
#define VALUE_ACTION_LOGIN_VERIFY               @"login_verify"

#define VALUE_ACTION_ORDER_CONFIRM_ORDER_BESPEAK    @"order_confirm_order_bespeak"
#define VALUE_ACTION_ORDER_INSERT_ORDER_BESPEAK     @"order_insert_order_bespeak"
#define VALUE_ACTION_GET_SYSTEM_MESSAGE_CATS        @"get_system_message_cats"
#define VALUE_ACTION_GET_SYSTEM_CAT_MESSAGE         @"get_system_cat_message"
#define VALUE_ACTION_QUICK_BOOK                 @"quick_book"

#define VALUE_ACTION_EXPIRE_COUPON_LIST         @"expire_coupon_list"

#define VALUE_ACTION_GET_CPORDER_INFO           @"get_cporder_info"
#define VALUE_ACTION_GET_COURT_POLL_INFO        @"get_court_pool_info"
#define VALUE_ACTION_COURT_POLL_LIST            @"court_pool_list"
#define VALUE_ACTION_COURT_POLL_INFO        @"court_pool_info"
#define VALUE_ACTION_GET_ADD_JPUSH_TAG          @"add_jpush_tag"
#define VALUE_ACTION_UPDATE_PUSH_TOKEN          @"update_push_token"
#define VALUE_ACTION_COURT_POOL_USER_LIST   @"court_pool_user_list"

#define VALUE_ACTION_GET_COURTJOIN_LIST            @"get_courtjoin_list"

//1.99临时接口,分享场地意愿调查
#define VALUE_ACTION_SUBMIT_SURVEY              @"add_survey"

//1.991 增加QYDToken
#define VALUE_ACTION_GET_QYD_TOKEN          @"get_qyd_token"

//2.0 打卡相关
#define VALUE_ACTION_GET_SIGN_IN_VENUES         @"get_signin_venues"
#define VALUE_ACTION_GET_MOTION_RECORDS         @"get_motion_records"
#define VALUE_ACTION_SIGN_IN                    @"sign_in"
#define VALUE_ACTION_WRITE_SIGN_IN_DIARY        @"sign_in_diary"
#define VALUE_ACTION_GET_SIGN_IN_DIARY          @"get_sign_in_diary"
//2.0 球局相关
#define VALUE_ACTION_LAUNCH_COURT_JOIN          @"launch_court_join"
#define VALUE_ACTION_UPDATE_COURT_JOIN_DESC     @"update_cj_desc"
#define VALUE_ACTION_GET_COURT_JOIN_ORDER_INFO  @"get_court_join_order_info"
//2.0.0
#define VALUE_ACTION_GET_COURTJOIN_INFO         @"get_courtjoin_info"
#define VALUE_ACTION_WRITE_SIGN_IN_DIARY        @"sign_in_diary"

//2.1.0
#define VALUE_ACTION_GET_BUSINESS_GOODS_LIST    @"get_business_goods_list"
#define VALUE_ACTION_SET_USERCARD_CONFIRM       @"set_usercard_confirm"
#define VALUE_ACTION_SET_USERCARD_BIND          @"set_usercard_bind"
#define VALUE_ACTION_SET_COMMENT_USEFUL         @"set_comment_useful"
#define VALUE_ACTION_SUBMIT_VENUES_MISTAKE      @"submit_venues_mistake_message"

//**************** network result code *******************

#define STATUS_SUCCESS                          @"0000"
#define STATUS_UKNOW_ERROR                      @"0001"
#define STATUS_PHONE_ALREADY_BEEN_REGISTERED    @"0020" //手机号码已经被注册

#define STATUS_NOT_REGISTER                     @"0201" //该手机号码未注册
#define STATUS_NO_PASSWORD                      @"0223" //该手机号码没有密码，属于快速登录用户
#define STATUS_SOLD                             @"0308" //场次或人次已售完错误码
#define STATUS_UNPAID_ORDER                     @"0309" //有未支付的订单

#define STATUS_BALANCE_PAY_SUCCESS              @"1302" //余额支付成功
#define STATUS_MONTH_CARD_PAY_SUCCESS           @"1305" //月卡支付成功

#define STATUS_HAVE_BEEN_PAID_BEFORE            @"0400" //订单之前已经支付过

#define STATUS_PAY_PASSWORD_WRONG               @"1203" //支付密码验证失败
#define STATUS_DUPLICATE_PAY_PASSWORD           @"1204" //重复设置支付密码
#define STATUS_DUPLICATE_PASSWORD               @"0214" //重复设置登录密码

#define STATUS_CARD_INVALID                     @"1410"  //月卡不存在
#define STATUS_CARD_NO_IMAGE                    @"1412"  //没有上传
#define STATUS_CARD_FROZEN                      @"1414"  //冻结
#define STATUS_CARD_EXPIRE                      @"1415"  //已过期
#define STATUS_CARD_ONCE_PER_DAY                @"1415"  //每天毁约一次
#define STATUS_CARD_CANCEL_TRIPLE               @"1416"  //毁约三次

#define STATUS_USER_CARD_INVALID                @"1023"  //会员卡异常
#define STATUS_LOGIN_ENCODE_ERROR               @"0225"  //Get Access Token的时候，loginEncode失败
#define STATUS_INSURANCE_ERROR                  @"5010"  //确认订单保险时间错误

#define STATUS_ACCESS_TOKEN_ERROR               @"-15"  //access token 失败

#define STATUS_NO_RESULT                        @"0100" //无数据

